### ISSUE TITLE
Site admin password

### ISSUE THREAD

**Issue by sylekta** [kso512/install-check_mk-server#1]
Hello, I just found your role and having a play. It looks like when the omd site is created, default behavior is to echo the cmkadmin password. After installing with your role, I was able to get the password from the omd-create.log but not really ideal if I want to do further automation after the install role is finished.

In the log it says you can change the admin password by running 'htpasswd -m ~/etc/htpasswd cmkadmin' as the site user, perhaps a task that runs that with a var to change to a password you specify? Unfortunately it prompts you for the new password and confirmation so I am not sure how to do that. Do you have any ideas?

**Comment by kso512** [comment]
Hi sylekta,

Great question!

I took a look at the [man page for htpasswd](https://httpd.apache.org/docs/2.4/programs/htpasswd.html), and it looks like you can send the password via the command line with the -b flag.

After the site's created, pass something like this via a "command" task:
`htpasswd -i ~/etc/passwd cmkadmin {{install_check_mk_server_cmkadmin_pw}}`

I see that in Ansible 2.3 there's a module for managing htpasswd files: 
https://docs.ansible.com/ansible/2.3/htpasswd_module.html

It's probably time for me to increase the Ansible version specified in the meta section from 2.2 to something higher.  Doing so would make it easier to leverage the built-in module and avoid the "command" task workaround in the long run.

Thanks for taking a look at this role and especially for the feedback.  I wasn't quite sure how to gracefully handle the password being set, and this helps!

- Chris

**Comment by sylekta** [comment]
I also found that module, but having issues with permissions on the tmp files and becoming an unprivileged user (the omd site user), so trying to get pipelining going which apparently gets around it.

**Comment by sylekta** [comment]
Cool that works,

```
- name: Make sure we can use htpasswd module
  apt: 
   name: python-passlib 
   state: present
- name: change site admin password
  htpasswd:
   path: /omd/sites/{{site_name}}/etc/htpasswd
   name: cmkadmin
   password: "{{site_admin_pass}}"
  become: true
  become_user: "{{site_name}}"
  vars:
    ansible_ssh_pipelining: yes
```
