### ISSUE TITLE
CentOS 8 Support

### ISSUE THREAD

**Issue by jwhb** [kso512/install-check_mk-server#5]
I tried using this role against CentOS 8.0 with Ansible 2.9.2 and encountered the following issues:

DNF
---
For CentOS 8.0 the fact `ansible_os_family` will have the value `dnf`. Therefore the yum installation steps will be skipped.

My dirty fix was to override this fact to use `yum` as preferred package manager. The proper fix would be to add dnf blocks to the tasks file.

PowerTools Repo
----------

The required package `graphviz-gd` was not found during installation. CentOS 7 had it in Base repository, but it was moved to the PowerTools repo. We can enable this repo with yum config-manager.

SELinux
-------

After the installation was successful I was shown "OMD: Site Not Started" instead of the web interface. SELinux was enabled on my installation and it prevented the webserver from connecting to the CMK backend at port 5000. @kso512 warned us about SELinux.

We can resolve this with the command `setsebool -P httpd_can_network_connect 1` or with Ansible, of course.

python-passlib
---------------

Package `python-passlib` also isn't available in CentOS default repositories. I fixed this by replacing it with `python3-passlib` in variable `install_check_mk_server_prereqs` in `tasks/CentOS.yaml`.

Playbook with fixes
-----------------

```yaml
---

- hosts: satellites
  pre_tasks:
    - name: Apply EL8 fixes
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= 8
      block:
        - name: Use yum as preferred package manager
          set_fact: ansible_pkg_mgr=yum
        - name: Enable PowerTools repository
          shell: |
            dnf config-manager --set-enabled PowerTools
        - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
          seboolean:
            name: httpd_can_network_connect
            state: yes
            persistent: yes
  roles:
    - role: geerlingguy.repo-epel
    - role: install-check_mk-server
```
